# Generated by Django 6.0.5 on 2026-06-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regitrar_empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='deducible_dependientes',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='deducible_medicina',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='deducible_vivienda',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='equipo_computo',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='extranjero',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pago_por_dias',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='parqueadero',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pensionado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='poliza_salud',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='poliza_vida',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='reside_extranjero',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tarjeta_credito',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='variable',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
