# Generated by Django 6.0.5 on 2026-06-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regitrar_empleados', '0002_alter_empleado_deducible_dependientes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_dane', models.CharField(max_length=10)),
                ('codigo_departamento', models.CharField(max_length=5)),
                ('codigo_pais', models.CharField(max_length=5)),
                ('nombre_ciudad', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudades',
                'ordering': ['nombre_ciudad'],
            },
        ),
    ]
