# Generated by Django 6.0.5 on 2026-06-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regitrar_empleados', '0003_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costos',
                'db_table': 'centro_costos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Subcliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Subcliente',
                'verbose_name_plural': 'Subclientes',
                'db_table': 'subclientes',
                'ordering': ['nombre'],
            },
        ),
    ]
