# Generated by Django 6.0.5 on 2026-07-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regitrar_empleados', '0004_centrocosto_subcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='ciudad_exp_documento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sabado_habil',
            field=models.CharField(blank=True, default='0', max_length=1, null=True),
        ),
    ]
